name: Comment when opened
run-name: ${{ github.actor }} is learing GitHub Actions
on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}
  #schedule:
  #- cron: '0 */4 * * *'

concurrency:
  group: build-and-test-on-push


jobs:
  build-and-test:
    name: Build and Test on Push
    runs-on: ubuntu-latest
    steps:
      - name: Build the code
        run: |
          echo "Starting code build"
          sleep 2m
          echo "Finish code buikd"
      - name: Test the code
        run: |
          echo "Starting code TEst"
          sleep 2m
          echo "Finish Test code"