name: Comment when opened
run-name: ${{ github.actor }} is learning GitHub Actions again
on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

concurrency:
  #group: build-and-test-on-push
  group: test-on-push-${{ github.head_ref }}
  cancel-in-progress: true


jobs:
  build-and-test:
    name: Build and Test on Push
    runs-on: ubuntu-latest
    steps:
      - name: Build the code
        run: |
          echo "${{ github.head_ref }}"
          echo "Starting code build"
          sleep 2m
          echo "Finish code buikd"
      - name: Test the code
        run: |
          echo "Starting code TEst"
          sleep 2m
          echo "Finish Test code"