name: Comment when opened
run-name: ${{ github.actor }} is learning GitHub Actions again
on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

concurrency:
  #group: build-and-test-on-push
  group: test-on-push-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  build-and-test:
    name: Build and Test on Push
    runs-on: ubuntu-latest
    steps:
      - name: output ref head
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >>$GITHUB_OUTPUT
          echo "${GITHUB_OUTPUT}"
      - name: Build the code
        run: |
          echo "Starting code build"
          sleep 2
          echo "Finish code buikd"
      - name: Test the code
        run: |
          echo "Starting code TEst"
          sleep 2
          echo "Finish Test code"

  get-cluster:
    runs-on:
      - ubuntu-latest
    outputs:
     cluster: '${{ steps.get-cluster-step.outputs.cluster}}'
    steps:
      - id: get-cluster-step
        run: >-
          echo -n "::set-output name=cluster::cluster=" ; echo
          ${{secrets.CLUSTER_NAME}} | base64 --decode

          run: echo "{name}={value}" >> $GITHUB_STATE
