name: Comment when opened
on:
  push:
   branches:
     - 'main'
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue comment TESTING --body "Thank you for opening this issue!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}