name: Comment when opened
run-name: ${{ github.actor }} is learing GitHub Actions
on: [push]
  workflow_dispatch: {}
  schedule:
  - cron: '0 */4 * * *'
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3