name: Comment when opened
run-name: ${{ github.actor }} is learing GitHub Actions
on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}
  schedule:
  - cron: '0 */4 * * *'
jobs:
  run-tests:
    env:
      IS_PIPELINE: 'true'
      NAMESPACE: lram
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: pre-check
        run: |
            echo "Log Level : $LEVEL"
            echo "Test: $NAMESPACE"
            echo "Env"
        env:
          LEVEL: "max"
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#          ref: main