name: Comment when opened
run-name: ${{ github.actor }} is learing GitHub Actions
on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}
  schedule:
  - cron: '0 */4 * * *'

jobs:
  build:
    needs: get-cluster
    runs-on: '${{needs.get-cluster.outputs.cluster}}'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: pre-check
        run: |
            echo "Log Level : $LEVEL"
            echo "Test: $NAMESPACE"
            echo "Env"
        env:
          LEVEL: "max"
  get-cluster:
    runs-on:
      - self-hosted
      - linux
    output:
      cluster: '${{ steps.get-cluster-step.outputs.cluster}}'
    steps:
      - id: get-cluster-step
        run: >-
          echo -n "::set-output name=cluster::cluster=" ; echo
          ${{secrets.CLUSTER_NAME}} | base64 --decode
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#          ref: main